### ISSUE TITLE
A bunch of letterforms are missing from defaultLetterMap

### ISSUE THREAD

**Issue by gilgamec** [mstksg/advent-of-code-ocr#1]
As near as I can tell, there are quite a few letterforms missing from the `defaultLetterMap`.

```haskell
λ> sort $ M.elems $ OCR.getLetterMap OCR.defaultLetterMap
"AABBCCEEFFGGHHIJJKKLLNOPPRX"
```

It looks like it's missing one of the Rs, the U, the Y, and both Zs.

**Comment by gilgamec** [comment]
I think the problem is that spurious spaces are getting into the string literal somehow:

```haskell
λ> raw1 = bimap id (filter (/=' ')) $ OCR.rawLetterforms1 
λ> sort $ M.elems $ OCR.getLetterMap $ uncurry OCR.parseLetterMap raw1
"ABCEFGHIJKLOPRUYZ"
```

Maybe a problem with `heredoc`?

**Comment by mstksg** [comment]
Ah, thank you...this is definitely interesting, and concerning!  I wonder what is going on here...it does sound like it could be a problem with the heredoc.  I should probably also build some fuzz testing for this instead of relying on some built in forms.

**Comment by mstksg** [comment]
I've added a filter to the heredocs, this seems to resolve the issue for now. But I do wonder what's happening.

**Comment by mstksg** [comment]
Ah! It might be a locale thing, since checking `defaultLettermap` on my machine gives the full alphabet.  What OS are you using?

**Comment by gilgamec** [comment]
I'm on MacOS 10.13.

**Comment by mstksg** [comment]
hm..definitely interesting.

i'm closing this issue because I've implemented the filtering change mentioned, but it would be interesting to investigate this further on the heredoc side. thanks opening!
